# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Login_SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Login_SwiftUI
  pod 'LineSDKSwift'

  target 'Login_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Login_SwiftUIUITests' do
    # Pods for testing
  end

end
